### PR TITLE
Add method to specify a random string of minimum and maximum length.

### PR DESCRIPTION
**Pull request by tamarbuta**
Added a string method in the **misc** provider to generate a random string of min and max length.

### CODE REVIEW

**Comment by fcurella** [comment]
Thanks @tamarbuta 

I'd rather have this in the `pystr` provider: https://github.com/joke2k/faker/blob/master/faker/providers/python/__init__.py#L27

I think the `min_chars` should be optional and default to `None`. If it's `None`, the string will have the previous behavior: fixed length of `max_chars`

**Comment by tamarbuta** [comment]
@fcurella Thanks for the feedback. Made the modifications to allow a `min_chars` specification in `pystr` and removed `string` from `misc`.

**Comment by tamarbuta** [comment]
@fcurella Didn't mean to close the PR. I though "close" meant close the comment preview... Newbie mistake. :)

**Comment by fcurella** [comment]
looks good!

can you add this quick test to https://github.com/joke2k/faker/blob/master/faker/tests/__init__.py#L528:

```python
characters = provider.pystr(min_chars=10, max_chars=255)
self.assertTrue((len(characters) >= 10)
```

**Comment by tamarbuta** [comment]
@fcurella Added unit test.

**Comment by fcurella** [comment]
Thanks @tamarbuta! Good work! ✨

**Pull request merged**
