### PR TITLE
Add no-NO datetime provider

### PR DESCRIPTION
**Pull request by zerogonal**
Added datetime provider for no_NO locale.

### CODE REVIEW

**Comment by zerogonal** [comment]
@fcurella I suggest that you put all of my pull requests up to this point into one big version bump.

**Comment by fcurella** [comment]
@zerogonal the file [faker/providers/date_time/no_NO/__init__.py](https://github.com/joke2k/faker/pull/1644/commits/e25145780a01b424fb25d377e5fd1478ec0e941b#diff-65b5a5d677b547f7f2346d93ceb306174bbedc7b3582fd2c731a63a0d6b3e02f) appears to be empty

**Comment by zerogonal** [comment]
oops....one second

**Comment by zerogonal** [comment]
@fcurella done

**Review by fcurella — APPROVED** [review]
Thank you!

**Pull request merged**
