### PR TITLE
Added Providers for ```ka_GE``` language

### PR DESCRIPTION
**Pull request by onesch**
### What does this change

New providers have been added: date_time, phone_numbers, job and colors for the ka_GE language.

### What was wrong

this localization did not exist

### How this fixes it

I added providers along the following paths:
```
faker/providers/color/ka_GE/__init__.py
faker/providers/date_time/ka_GE/__init__.py
faker/providers/job/ka_GE/__init__.py
faker/providers/phone_number/ka_GE/__init__.py
```
Checklist
- [x] I have read the documentation about [CONTRIBUTING](https://github.com/joke2k/faker/blob/master/CONTRIBUTING.rst)
- [x] I have run ```make lint```

### CODE REVIEW

**Comment by onesch** [comment]
Can I write ideas for "improving the code" in "Issues"?

**Review by fcurella — CHANGES_REQUESTED** [review]
Can you add some tests?

**Comment by onesch** [comment]
> Can you add some tests?

I can add tests but they will be similar to others ok?

**Comment by onesch** [comment]
what's the problem? I have the same errors as [#2112](https://github.com/joke2k/faker/commit/b605d2118b2e5879795678d4e234bd3552fee0a9)

**Review by fcurella — APPROVED** [review]
Thank y ou!

**Comment by onesch** [comment]
> Thank y ou!

I'm waiting for your version ```30.3.0``` to pass the tests.

**Comment by onesch** [comment]
[Went well](https://github.com/joke2k/faker/actions/runs/11220466114/job/31188995413?pr=2110), please accept. 🙂

**Pull request merged**
