### PR TITLE
Add official support for python 3.12

### PR DESCRIPTION
**Pull request by pfouque**
### What does this change

Add Python 3.12 support

### What was wrong

Nothing! 
(just a remaining Python 3.7 trove classifier in setup.py)

### How this fixes it

Adding 3.12 in CI + setup.py, that's all!

Fixes #...

### CODE REVIEW

**Comment by stefan6419846** [comment]
How is dropping PyPy testing related to Python 3.12?

**Comment by pfouque** [comment]
It is not 😅
It generated a segmentation fault on the CI so I wanted to check if the CI passes without.
I was also wondering why is it the only pypi version tested

**Comment by pfouque** [comment]
Ok, it worked fine this time! 🎊

**Review by fcurella — APPROVED** [review]
Thank you!

**Pull request merged**
