### PR TITLE
Improve pydecimal provider with min and max values

### PR DESCRIPTION
**Pull request by leo-naeka**
### What does this change

Improve numbers generation through the pydecimal provider, especially with `min_value` and `max_value`.

### What was wrong

The pydecimal provider was not accepting floats or decimals for min and max value boundaries.  
Hence it was not possible to cover some cases, like scoped percent values (consider any N-decimal number between 73,5% and 98%, so with `min_value=D("0.735")` and `max_value = D("0.98")`).

### How this fixes it

Support decimals and floats for `min_value` and `max_value`. Improve right number generation accordingly.

### CODE REVIEW

**Review by fcurella — COMMENTED** [review]
Thank you! Would you mind adding type hints to the signature?

**Comment by leo-naeka** [comment]
> Thank you! Would you mind adding type hints to the signature?

For sure!

**Comment by leo-naeka** [comment]
Just realized that I missed some bits… Fixed now.

The remaining mypy errors concern `abs()` return inferred as `object` (see https://github.com/python/mypy/issues/8601).

Tried wrapping it but not really convinced. Your thoughts on this?

**Comment by fcurella** [comment]
ok, lwt's just not add the type hint for now. Sorry for the extra work

**Pull request closed without merging**
