### PR TITLE
Add sk_SK Job provider

### PR DESCRIPTION
**Pull request by pipozzz**
### What does this changes

This PR adds sk_SK Job provider

### CODE REVIEW

**Comment by fcurella** [comment]
Thank you @pipozzz ! Do you have a source for the data that we can include in the file?

**Comment by pipozzz** [comment]
I derived it from base job provider

**Review by fcurella — CHANGES_REQUESTED** [review]

**Comment by pipozzz** [comment]
Yes I translated it :)

**Review by fcurella — APPROVED** [review]

**Comment by fcurella** [comment]
Thank you!

**Pull request merged**
