### PR TITLE
Hungarian! 

### PR DESCRIPTION
**Pull request by chrisvoncsefalvay**
Some Hungarian 🇭🇺 generators, including:

- place names, both fictitious and real, 
- addresses (with realistic street names!),
- peeps, with real recent name frequency distributions,
- phone numbers, and
- the crowning glory 🤴  - Hungarian SSN (személyazonosító szám)!

🇭🇺

### CODE REVIEW

**Comment by chrisvoncsefalvay** [comment]
Needs: some tests to be written. I might do that over the next few days, schedules willing.

**Comment by fcurella** [comment]
Thanks! can you also add `hu_HU` to the lists in the [README](https://github.com/joke2k/faker/blob/master/README.rst#localization) and the [docs](https://github.com/joke2k/faker/blob/master/docs/index.rst#localization)?

**Comment by fcurella** [comment]
I went ahead and merged this. Thank you fro your contribution! ✨

**Comment by chrisvoncsefalvay** [comment]
@fcurella I'm so sorry, I only just saw this... my apologies! Thanks for the merge.

**Pull request merged**
