### PR TITLE
Fixes #1352 Missing tests in various address providers

### LINKED ISSUE #1352: Missing tests in various address providers
* Faker version: 5.0.2
* OS: Mac OS Big Sur

While creating another provider for a PR and doing it's necessary tests, I noticed that there are some address providers that don't have tests. I think that every provider should have it's test for uniformity and assurance that the provider works, but I don't know if they are really necessary. The list of address providers without tests are: 

- [ ] en_NZ
- [ ] fil_PH
- [ ] fr_CH
- [ ] hu_HU
- [ ] id_ID
- [ ] it_IT
- [ ] ka_GE
- [ ] ko_KR
- [ ] sk_SK
- [ ] si_SI
- [ ] sv_SE
- [ ] tl_PH
- [ ] uk_UA

Should this tests be added?

### PR DESCRIPTION
**Pull request by Kalbra**
The following changes were made see #1352:
- en_NZ: Adding tests
- fil_PH: Already implemented
- fr_CH: Adding tests
- hu_HU: Adding tests
- id_ID: Adding tests
- it_IT: Adding more tests
- ka_GE: Adding tests
- ko_KR: Adding more tests
- sk_SK: Already implemented
- sl_SI: Adding tests
- sv_SE: Adding tests
- tl_PH: Already implemented
- uk_UA: Adding tests

### CODE REVIEW

**Review by fcurella — CHANGES_REQUESTED** [review]
Thank you! Could you fix the linting issues?

**Comment by Kalbra** [comment]
I reformated the files by using `black --line-length 120` like discribed in the style guide.
I also deleted double `TestEnNz` and `TestHuHu` classes

**Review by fcurella — CHANGES_REQUESTED** [review]
Running `make lint` will run `black` and `isort` with the correct settings.

There are also a couple of unused imports. Could you remove them?

**Comment by fcurella** [comment]
Thank you!

**Pull request merged**
