### PR TITLE
Added swiss names (de_CH)

### PR DESCRIPTION
**Pull request by DanEEStar**
Do I have to do other things/steps?

### CODE REVIEW

**Comment by fcurella** [comment]
Thank you @DanEEStar ,

I'm not sure how we should handle the Swiss case. I know Switzerland has many official languages, and the names contained in this PR sounds Italian, French and German.

I'm not familiar with common practices in Switzerland re: locales.

Is `de_CH` used as de-facto 'default'? Alternatively, we could also add `it_CH` and `fr_CH` (which could simply subclass from `de_CH`).

What do you think would be more appropriate?

**Comment by Hopiu** [comment]
I'd say it generally doesn't make sense to have de_CH as the _CH default. As I saw you already added the data for fr_CH to the repo.

If you are unhappy with the names @DanEEStar provided I'd be willing to revise them on the base of the data provided by the Swiss government.
(Available at https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/geburten-todesfaelle/vornamen-schweiz.html)

**Comment by DanEEStar** [comment]
@Hopiu I was also thinking about updating this pull-request recently.
What are your thoughts about the French and Italian "sounding" names in the dataset. In my opinion it is not that uncommon for a German speaking swiss person to have a French or Italian name.

**Comment by fcurella** [comment]
I'd much rather have names from a governmental source. Not sure if there are separate lists for the different Swiss locales. If not, we can just use the same list for all of them.

**Comment by Hopiu** [comment]
@DanEEStar Have a look at the link I provided. You'll find official excel sheets containing the most common names in Switzerland separated by sex and language region.
You will still find some French and Italian "sounding" names there.

**Comment by DanEEStar** [comment]
@Hopiu The list contains only first names though. Do you know any statistical source for last names.

I have a list with about 100000 swiss persons with names and language from which I extracted and aggregated the data for the first pull request.
But the list is not officially public...

**Comment by nfrei** [comment]
@fcurella Can this be merged? I think it's a decent list of Swiss names.
By the way, there is already localization for Swiss french (fr_CH) on at least jobs and addresses in faker. So it's just consistent to include de_CH as well.

**Pull request merged**
