### PR TITLE
Added Company Provider for tr_TR locale.

### PR DESCRIPTION
**Pull request by iamnotagentleman**
Added Company Provider for tr_TR locale. 👍

### CODE REVIEW

**Comment by fcurella** [comment]
@iamnotagentleman you can split the imports into groups, and `isort` will sort them independently:

```python
from faker.providers.company.ja_JP import Provider as JaJpCompanyProvider
from faker.providers.company.nl_NL import Provider as NlNlCompanyProvider
from faker.providers.company.pl_PL import Provider as PlPlCompanyProvider
from faker.providers.company.tr_TR import Provider as TrTrCompanyProvider

from faker.providers.company.pl_PL import company_vat_checksum, local_regon_checksum, regon_checksum
from faker.providers.company.pt_BR import company_id_checksum
from faker.providers.company.ru_RU import Provider as RuRuCompanyProvider
from faker.providers.company.ru_RU import calculate_checksum
```

**Comment by iamnotagentleman** [comment]
> @iamnotagentleman you can split the imports into groups, and `isort` will sort them independently:
> 
> ```python
> from faker.providers.company.ja_JP import Provider as JaJpCompanyProvider
> from faker.providers.company.nl_NL import Provider as NlNlCompanyProvider
> from faker.providers.company.pl_PL import Provider as PlPlCompanyProvider
> from faker.providers.company.tr_TR import Provider as TrTrCompanyProvider
> 
> from faker.providers.company.pl_PL import company_vat_checksum, local_regon_checksum, regon_checksum
> from faker.providers.company.pt_BR import company_id_checksum
> from faker.providers.company.ru_RU import Provider as RuRuCompanyProvider
> from faker.providers.company.ru_RU import calculate_checksum
> ```

got it

**Comment by iamnotagentleman** [comment]
still the same error, weird. @fcurella

**Comment by fcurella** [comment]
@iamnotagentleman Can you just sort them the way the CI wants them?

**Comment by iamnotagentleman** [comment]
@fcurella Ready to GO! 💯

**Review by fcurella — APPROVED** [review]

**Pull request merged**
