### PR TITLE
added faker_vehicle provider

### PR DESCRIPTION
**Pull request by kennethwsmith**
https://pypi.org/project/faker-vehicle/
https://github.com/kennethwsmith/faker_vehicle
https://travis-ci.org/github/kennethwsmith/faker_vehicle
https://coveralls.io/github/kennethwsmith/faker_vehicle

### What does this changes

Added faker_vehicle provider

### CODE REVIEW

**Comment by fcurella** [comment]
Thank you! You'll have to also add a link at the botton of the `.rst` for the link to work.

**Comment by kennethwsmith** [comment]
oops, fixed.  Thanks

**Comment by fcurella** [comment]
Thank you! ✨

**Comment by malefice** [comment]
@fcurella I think you forgot to accept this PR.

**Comment by fcurella** [comment]
whoops! Thank you for keeping tabs @malefice !

**Pull request merged**
