### PR TITLE
Added Providers for `uz_UZ` language

### PR DESCRIPTION
**Pull request by laziest-coder**
### What does this change
New providers have been added for `uz_UZ` language.

### What was wrong
The support for Uzbek language did not exist.

### How this fixes it
I've added following providers:
* date_time
* color
* person
* currency
* phone_number

### Checklist

- [x] I have read the documentation about [CONTRIBUTING](https://github.com/joke2k/faker/blob/master/CONTRIBUTING.rst)
- [x] I have read the documentation about [Coding style](https://github.com/joke2k/faker/blob/master/docs/coding_style.rst)
- [x] I have run `make lint`

### CODE REVIEW

**Comment by laziest-coder** [comment]
Hey @fcurella! Not sure why some tests are failing, would you direct me on how can I fix it?

**Comment by laziest-coder** [comment]
Also, I wonder if it's possible to add label `hacktoberfest-accepted` to the PR since I'm participating in [hacktoberfest](https://hacktoberfest.com/) organized by [DigitalOcean](https://www.digitalocean.com/)

**Review by fcurella — CHANGES_REQUESTED** [review]
As per our [Coding Style](https://github.com/joke2k/faker/blob/master/docs/coding_style.rst#data-sets), could you add sources for the names in the person provider?

**Comment by laziest-coder** [comment]
> As per our [Coding Style](https://github.com/joke2k/faker/blob/master/docs/coding_style.rst#data-sets), could you add sources for the names in the person provider?

Previous names were generated from ChatGPT, now I've shortened the list to top 100 names and added the source.

**Review by fcurella — APPROVED** [review]
Thank you!

**Pull request merged**
