### PR TITLE
Tune Person, cs_CZ

### PR DESCRIPTION
**Pull request by george0st**
### What does this change

Tune content of Person for cs_CZ, I added a few names, degrees and suffixes

### What was wrong

Only improvement, I missed a few common things for cs_CZ

Many thanks for merge.

### CODE REVIEW

**Comment by george0st** [comment]
@fcurella , please merge

**Review by fcurella — CHANGES_REQUESTED** [review]
I realize this provider didn't have a source to begin with, but do you have a source for the new  data?

**Comment by george0st** [comment]
Hi @fcurella , thx for info, about sources:

- Calendar for cs_CZ names see https://www.zlate-mince.cz/jmena_ceskeho_kalendare.htm

- Degrees for cs_CZ see https://eprehledy.cz/ceske_tituly.php

BTW: Let me know and I will add these public sources to relevant place in GIT

**Comment by fcurella** [comment]
Thank you @george0st ! Would you add these links as comments in the provider's code?

**Review by fcurella — APPROVED** [review]
Thank you!

**Pull request merged**
