### PR TITLE
Command improvements

### PR DESCRIPTION
**Pull request by cbaines**
Thanks for writing fake-factory (or faker, still a little confused about the name) and releasing it as free software, I am using it for several projects.

While writing a man page for faker, as part of packaging it for Debian, I noticed that the help given when passing --help was a little lacking. While attempting to improve this, I also noticed that the fake argument was oddly structured, so I changed that also.

### CODE REVIEW

**Comment by fcurella** [comment]
@cbaines does splitting the `fake` argument change the way the CLI should be called? In other words, does [this section](https://github.com/joke2k/faker#command-line-usage) of the `README` need to be changed?

**Comment by fcurella** [comment]
@cbaines FYI, I'm looking at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816169 and it mentions the license as 'Expat', when in fact `faker` is released under MIT.

**Comment by cbaines** [comment]
> @cbaines does splitting the fake argument change the way the CLI should be called? In other words, does this section of the README need to be changed?

It does not change the way in which it should or can be called, but its probably worth updating the README to be more consistent with the --help output (which this branch goes some way to doing). I'll add another commit improving this shortly.

**Comment by cbaines** [comment]
> @cbaines FYI, I'm looking at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816169 and it mentions the license as 'Expat', when in fact faker is released under MIT.

MIT is an ambiguous name that sometime refers to the Expat license (as it does in the case of fake-factory/faker), see https://en.wikipedia.org/wiki/MIT_License#Various_versions for more information.

**Comment by fcurella** [comment]
Thanks for clarifyinf @cbaines, I wasn't aware of this subtlety. Nevermind
my comment re: the license.

**Comment by cbaines** [comment]
> Thanks for clarifyinf @cbaines, I wasn't aware of this subtlety. Nevermind my comment re: the license.

No problem :) I have now updated the README. The help output and it still differ, but I think that is ok, as I think the README is more helpful in some ways (e.g. abbreviating the language code list, and using `module.containing.custom.provider`).

**Comment by fcurella** [comment]
thanks! :sparkles:

**Pull request merged**
