### PR TITLE
[or_IN] Odia person's name added.

### PR DESCRIPTION
**Pull request by soumendrak**
### What does this changes

This adds [Odia language](https://simple.wikipedia.org/wiki/Odia_language) person names into the Faker.

### What was wrong

Odia language corpus was missing.

### How this fixes it

I have added Odia language corpus of names extracting from Odia Wikipedia into this PR. 

I have tested the following in local:
``` python
from faker import Faker
fake = Faker("or_IN")
fake.first_name()  # 'ସନତ'
fake.middle_name()  # 'ରାଣୀ'
fake.last_name()  # 'ନାଗେଶ'
```
Please validate and approve. Let me know if any changes need to be done in format.

### CODE REVIEW

**Comment by fcurella** [comment]
Thank you! Could you also add some tests?

**Comment by soumendrak** [comment]
@fcurella, test cases added. Please check.

**Comment by soumendrak** [comment]
@fcurella , Please let me know if anything pending from me.

**Comment by fcurella** [comment]
Thank you!

**Pull request merged**
