### PR TITLE
Add license plates and language names for he_IL locale

### PR DESCRIPTION
**Pull request by AndreyRub**
### What does this changes

> Adds license plates generation for he_IL locale
> Adds language names generation for he_IL locale
> Adds unit tests for both of the features above

### CODE REVIEW

**Review by fcurella — CHANGES_REQUESTED** [review]
Thank you! Could you fix the [linting issues](https://app.circleci.com/pipelines/github/joke2k/faker/946/workflows/f6f7950b-c3b2-4134-9fda-cc0247f5c3d0/jobs/2967?invite=true#step-103-3620) ?

**Comment by AndreyRub** [comment]
> Thank you! Could you fix the [linting issues](https://app.circleci.com/pipelines/github/joke2k/faker/946/workflows/f6f7950b-c3b2-4134-9fda-cc0247f5c3d0/jobs/2967?invite=true#step-103-3620) ?

Sure thing. Is there any way to check the linting issues without accessing CircleCI? For some reason, it does not work for me. Maybe there is some local command that I can run?

**Comment by AndreyRub** [comment]
Ok I think I figured out - flake8 utility can be used. I think it solves all of the issues

**Comment by fcurella** [comment]
Thank you so much!

**Pull request merged**
