### PR TITLE
Accept step argument in random_int()

### PR DESCRIPTION
**Pull request by francoisfreitag**
### What does this changes

Allows selecting a subset of integers in a range, for example even integers.

### What was wrong

Could not select a random even number with `pyint()`.

### How this fixes it

Accept step argument in random int

### CODE REVIEW

**Comment by fcurella** [comment]
Thank you! ✨

**Comment by fabien-michel** [comment]
Keyword args (min, and max) are not consistent with pyfloat and pydecimal (min_value and max_value)...

**Comment by francoisfreitag** [comment]
That's right, I'll look into harmonizing these.

**Comment by francoisfreitag** [comment]
> Keyword args (min, and max) are not consistent with pyfloat and pydecimal (min_value and max_value)

https://github.com/joke2k/faker/pull/957

**Pull request merged**
