### PR TITLE
use f-strings

### PR DESCRIPTION
**Pull request by eumiro**
We are at Python 3.6+, so replace (most) string formatting with f-strings.
This is based on the current master, so some file names built in #1339 will be added after their merge and this rebase.

### CODE REVIEW

**Comment by eumiro** [comment]
Rebased after #1339.

**Comment by eumiro** [comment]
There are also quite many (but not 100%) cases of backticks used to highlight the value of a variable. Do they have any special purpose or would `…{value!r}…` with simple quotes and (what is more important) correctly escaped quotes within the string do the job as well?

**Comment by fcurella** [comment]
@eumiro I think the backticks are just for aesthetic purposes. Can you show me a specific example?

**Comment by eumiro** [comment]
> @eumiro I think the backticks are just for aesthetic purposes. Can you show me a specific example?

https://github.com/eumiro/faker/blob/f-strings/faker/cli.py#L41 contains the `!r` flags in an f-string. I find it better and safer than the explicit backticks elsewhere in the code and would change it accordingly.

**Comment by fcurella** [comment]
@eumiro I thought by "backticks" you meant the <code>`</code> character.

I would just keep the quotes the way they are. I don't really see a compelling reason to change them now.

**Comment by eumiro** [comment]
@fcurella rebased, repushed, fails at coveralls only.

**Comment by fcurella** [comment]
Thank you so much ✨

**Pull request merged**
