### PR TITLE
Typing [Fixed #1489!]

### LINKED ISSUE #1489: [Feature Request] Add Type Hints (stubs)
As people are preferring Type Hints and mypy is getting more popularity and as a developer, I also like Type hints. So, if there's will be type hinted library like this. It will be awesome 🤩

Current situation:
image

### PR DESCRIPTION
**Pull request by MarcelRobeer**
### What does this change?
Added type annotation hints to all functions/classes in `faker`!

### What was wrong

`faker` did not include type annotations (issue #1489).

### How this fixes it
- Added automatic type annotations with `monkeytype` (https://monkeytype.readthedocs.io/en/latest/) for all files in which it did not throw errors.
- Manual linter fixes.
- Manual fixes of missing type annotations or unknown type annotations (e.g. type `None`). Did a lot of code analysis myself, but would also like to credit @nicarl for his earlier work on type annotations (e.g. in `documentory.py` and `generator.py`).
- `mypy` compliant (`mypy -m faker`). **Also added `mypy -m faker` test to `tox.ini`!**
- `flake8` compliant (`flake8 faker tests`)
- `isort` compliant (`python3 -m isort --check-only --diff .`)

### CODE REVIEW

**Comment by MarcelRobeer** [comment]
Thanks! Happy to help :)

I would like to point out some specific difficulties I faced, so you can better understand my decisions made:
1. f5a9985b00df2cf161af85a0f0570702a996ea4b & 64a2bfded086c123150ced3911d135bfd37b527c: `providers/__init__.py` imports from `generators` and vice versa, resulting in a circular import error. I tried out a simple fix (i.e. only importing `from .providers import BaseProvider` in `generator.py` if `typing.TYPE_CHECKING`, but the ImportError then pops up when creating the coverage report on all OS-Python version combinations. As a current hotfix I replaced `BaseProvider` in `generator.py` with `object`. However, I would suggest for a future version to rethink generators having providers in them and providers linking to generators. Perhaps a factory pattern?
2. 28f7daaae7cfbd507e7e56c0a485bc55cd5dcc69: `typing.OrderedDict` was newly introduced in `Python 3.7.2`, but will be deprecated again in `Python 3.10` (https://www.python.org/dev/peps/pep-0585/). For now, in `typing.py` it attempts to import `typing.OrderedDict` and if this gets an `ImportError` (in Python 3.6) it falls back to the original `MutableMapping`. For `Python 3.10` compatibility check the Python (minor) version and import `collections.OrderedDict` instead ([which will support square bracket usage for typing](https://www.python.org/dev/peps/pep-0585/) `[]`).
3. 1bb4e059d7a0a4600aaa68f7204c794a9db2fe8b: `PyPy3` does not support `mypy`. It cannot even be pip-installed. Therefore, in `tox.ini` the install of the dependency was moved to within `[testenv:mypy]` and is skipped due to `skip_missing_interpreters=true`.

**Comment by fcurella** [comment]
Thank you for volunteering @nicarl !

**Comment by MarcelRobeer** [comment]
```bash
faker/providers/person/__init__.py:64: error: "Provider" has no attribute "formats_male"
faker/providers/person/__init__.py:72: error: "Provider" has no attribute "formats_nonbinary"
faker/providers/person/__init__.py:80: error: "Provider" has no attribute "formats_female"
faker/providers/person/__init__.py:88: error: "Provider" has no attribute "first_names_male"; maybe "first_name_male", "first_name_female", or "first_names"?
faker/providers/person/__init__.py:93: error: "Provider" has no attribute "first_names_nonbinary"; maybe "first_name_nonbinary", "last_name_nonbinary", or "name_nonbinary"?
faker/providers/person/__init__.py:98: error: "Provider" has no attribute "first_names_female"; maybe "first_name_female", "first_name_male", or "last_name_female"?
faker/providers/person/__init__.py:103: error: "Provider" has no attribute "last_names_male"; maybe "last_name_male", "last_name_female", or "last_names"?
faker/providers/person/__init__.py:108: error: "Provider" has no attribute "last_names_nonbinary"; maybe "last_name_nonbinary", "first_name_nonbinary", or "name_nonbinary"?
faker/providers/person/__init__.py:113: error: "Provider" has no attribute "last_names_female"; maybe "last_name_female", "last_name_male", or "first_name_female"?
faker/providers/person/__init__.py:118: error: "Provider" has no attribute "prefixes"; maybe "prefix"?
faker/providers/person/__init__.py:121: error: "Provider" has no attribute "prefixes_male"; maybe "prefix_male" or "prefix_female"?
faker/providers/person/__init__.py:121: error: "Provider" has no attribute "prefixes_female"; maybe "prefix_female" or "prefix_male"?
faker/providers/person/__init__.py:121: error: "Provider" has no attribute "prefixes_nonbinary"; maybe "prefix_nonbinary" or "suffix_nonbinary"?
faker/providers/person/__init__.py:125: error: "Provider" has no attribute "prefixes_male"; maybe "prefix_male" or "prefix_female"?
faker/providers/person/__init__.py:125: error: "Provider" has no attribute "prefixes_female"; maybe "prefix_female" or "prefix_male"?
faker/providers/person/__init__.py:131: error: "Provider" has no attribute "prefixes_male"; maybe "prefix_male" or "prefix_female"?
faker/providers/person/__init__.py:136: error: "Provider" has no attribute "prefixes_nonbinary"; maybe "prefix_nonbinary" or "suffix_nonbinary"?
faker/providers/person/__init__.py:141: error: "Provider" has no attribute "prefixes_female"; maybe "prefix_female" or "prefix_male"?
faker/providers/person/__init__.py:146: error: "Provider" has no attribute "suffixes"; maybe "suffix"?
faker/providers/person/__init__.py:149: error: "Provider" has no attribute "suffixes_male"; maybe "suffix_male" or "suffix_female"?
faker/providers/person/__init__.py:149: error: "Provider" has no attribute "suffixes_female"; maybe "suffix_female" or "suffix_male"?
faker/providers/person/__init__.py:149: error: "Provider" has no attribute "suffixes_nonbinary"; maybe "suffix_nonbinary" or "prefix_nonbinary"?
faker/providers/person/__init__.py:153: error: "Provider" has no attribute "suffixes_male"; maybe "suffix_male" or "suffix_female"?
faker/providers/person/__init__.py:153: error: "Provider" has no attribute "suffixes_female"; maybe "suffix_female" or "suffix_male"?
faker/providers/person/__init__.py:159: error: "Provider" has no attribute "suffixes_male"; maybe "suffix_male" or "suffix_female"?
faker/providers/person/__init__.py:164: error: "Provider" has no attribute "suffixes_nonbinary"; maybe "suffix_nonbinary" or "prefix_nonbinary"?
faker/providers/person/__init__.py:169: error: "Provider" has no attribute "suffixes_female"; maybe "suffix_female" or "suffix_male"?
```

For these issues they are working on a fix in `mypy` (see https://github.com/python/mypy/issues/11142). How should we resolve it for now?

**Comment by nicarl** [comment]
> ```shell
> faker/providers/person/__init__.py:64: error: "Provider" has no attribute "formats_male"
> faker/providers/person/__init__.py:72: error: "Provider" has no attribute "formats_nonbinary"
> faker/providers/person/__init__.py:80: error: "Provider" has no attribute "formats_female"
> faker/providers/person/__init__.py:88: error: "Provider" has no attribute "first_names_male"; maybe "first_name_male", "first_name_female", or "first_names"?
> faker/providers/person/__init__.py:93: error: "Provider" has no attribute "first_names_nonbinary"; maybe "first_name_nonbinary", "last_name_nonbinary", or "name_nonbinary"?
> faker/providers/person/__init__.py:98: error: "Provider" has no attribute "first_names_female"; maybe "first_name_female", "first_name_male", or "last_name_female"?
> faker/providers/person/__init__.py:103: error: "Provider" has no attribute "last_names_male"; maybe "last_name_male", "last_name_female", or "last_names"?
> faker/providers/person/__init__.py:108: error: "Provider" has no attribute "last_names_nonbinary"; maybe "last_name_nonbinary", "first_name_nonbinary", or "name_nonbinary"?
> faker/providers/person/__init__.py:113: error: "Provider" has no attribute "last_names_female"; maybe "last_name_female", "last_name_male", or "first_name_female"?
> faker/providers/person/__init__.py:118: error: "Provider" has no attribute "prefixes"; maybe "prefix"?
> faker/providers/person/__init__.py:121: error: "Provider" has no attribute "prefixes_male"; maybe "prefix_male" or "prefix_female"?
> faker/providers/person/__init__.py:121: error: "Provider" has no attribute "prefixes_female"; maybe "prefix_female" or "prefix_male"?
> faker/providers/person/__init__.py:121: error: "Provider" has no attribute "prefixes_nonbinary"; maybe "prefix_nonbinary" or "suffix_nonbinary"?
> faker/providers/person/__init__.py:125: error: "Provider" has no attribute "prefixes_male"; maybe "prefix_male" or "prefix_female"?
> faker/providers/person/__init__.py:125: error: "Provider" has no attribute "prefixes_female"; maybe "prefix_female" or "prefix_male"?
> faker/providers/person/__init__.py:131: error: "Provider" has no attribute "prefixes_male"; maybe "prefix_male" or "prefix_female"?
> faker/providers/person/__init__.py:136: error: "Provider" has no attribute "prefixes_nonbinary"; maybe "prefix_nonbinary" or "suffix_nonbinary"?
> faker/providers/person/__init__.py:141: error: "Provider" has no attribute "prefixes_female"; maybe "prefix_female" or "prefix_male"?
> faker/providers/person/__init__.py:146: error: "Provider" has no attribute "suffixes"; maybe "suffix"?
> faker/providers/person/__init__.py:149: error: "Provider" has no attribute "suffixes_male"; maybe "suffix_male" or "suffix_female"?
> faker/providers/person/__init__.py:149: error: "Provider" has no attribute "suffixes_female"; maybe "suffix_female" or "suffix_male"?
> faker/providers/person/__init__.py:149: error: "Provider" has no attribute "suffixes_nonbinary"; maybe "suffix_nonbinary" or "prefix_nonbinary"?
> faker/providers/person/__init__.py:153: error: "Provider" has no attribute "suffixes_male"; maybe "suffix_male" or "suffix_female"?
> faker/providers/person/__init__.py:153: error: "Provider" has no attribute "suffixes_female"; maybe "suffix_female" or "suffix_male"?
> faker/providers/person/__init__.py:159: error: "Provider" has no attribute "suffixes_male"; maybe "suffix_male" or "suffix_female"?
> faker/providers/person/__init__.py:164: error: "Provider" has no attribute "suffixes_nonbinary"; maybe "suffix_nonbinary" or "prefix_nonbinary"?
> faker/providers/person/__init__.py:169: error: "Provider" has no attribute "suffixes_female"; maybe "suffix_female" or "suffix_male"?
> ```
> 
> For these issues they are working on a fix in `mypy` (see [python/mypy#11142](https://github.com/python/mypy/issues/11142)). How should we resolve it for now?

I think in such case it is okay to use  `# type: ignore[attr-defined]`. We can activate a check for redundant type ignores in the mypy config, once mypy can handle `getattr` mypy will warn us and we can remove the ignore.

**Comment by MarcelRobeer** [comment]
> `# type: ignore[attr-defined]`

Applied this fix, am now down to 'only' 83 errors in 512 files :)

**Comment by MarcelRobeer** [comment]
> @MarcelRobeer I more or less fixed all the problems (with some `# type: ignore`). Do you think you can cherry pick the two last commits from https://github.com/nicarl/faker/tree/fix_last_type_errors

Did some minor changes, which also made some of the `# type: ignore` redundant. Also updated `docs/coding_style.rst` and added `mypy` to `.github/workflows/ci.yml`

**Comment by fcurella** [comment]
@MarcelRobeer I can do the squashing, no worries! :)

**Comment by MarcelRobeer** [comment]
> > I would suggest to keep this separate, since the lint step is only run on one Python version (3.9.7) and typing has had some major overhauls in 3.8 and 3.10. The current set-up runs mypy on 3.6, 3.8 and 3.10 to test all scenarios. Edit: Maybe we should add 'typing' to 'needs' in some places of the workflows/ci.yml file?
> 
> I agree in having it as a separate step. Ideally, I'd like to run it in parallel with the `lint` step, and before running the tests.

Implemented this. It now passes all tests. Note that I had to add the `--no-warn-unused-ignores` flag to `mypy` due to https://github.com/python/mypy/issues/8823

**Pull request merged**
