### PR TITLE
Add cs_CZ lorem - word list

### PR DESCRIPTION
**Pull request by jakubno**
### What does this changes

Add Czech lorem

### CODE REVIEW

**Comment by fcurella** [comment]
Thank you! Do you mind adding a test case?

**Comment by jakubno** [comment]
> Thank you! Do you mind adding a test case?

Sure, will do! Do you want to test all the methods of lorem (`paragraph`, `paragraphs`, `word`, `words`, `text`, `texts`)? Because all of them use the same word list, right?

**Comment by fcurella** [comment]
Test for each methods will be better to prevent regressions

**Comment by jakubno** [comment]
What do you think, should all names with first capital letter (countries, cities) be removed or lower cased?

**Comment by fcurella** [comment]
@jakubno I would say keep them the way they were in the original dataset

**Comment by jakubno** [comment]
I hope it's fine like that, but I am open to any suggestion how improve the tests :)

**Comment by fcurella** [comment]
Thank you! ✨

**Pull request merged**
