### PR TITLE
Replace archived `faker-optional` with my alternative

### PR DESCRIPTION
**Pull request by PerchunPak**
[`faker-optional`](https://github.com/lyz-code/faker-optional) was archived 9 months ago. I recently created an alternative to replace it.

### CODE REVIEW

**Comment by stefan6419846** [comment]
Just from a general development perspective: Does it really make sense to create a completely new repository without the old commit history and publish a new package under a different name when the original repository explicitly states:

> No longer maintained: I use [pydantic-factories](https://github.com/Goldziher/pydantic-factories) instead, if you want to maintain this repo, I can transfer it to you.

**Comment by PerchunPak** [comment]
I wrote the author, and he didn't answer for ~3 days. I also didn't take anything from the original repo, and wrote everything from zero.

If you look at [old implementation](https://github.com/lyz-code/faker-optional/blob/master/src/faker_optional/model.py), [and mine](https://github.com/PerchunPak/optional-faker/blob/master/optional_faker.py), you will see that they are completely different.

**Comment by stefan6419846** [comment]
Thanks for the explanations - I did not have a closer look at the actual code and you were speaking of a fork as well.

**Review by fcurella — APPROVED** [review]
Thank you!

**Comment by lyz-code** [comment]
I'm the author of the old code and I'm fine with the change. If I were quicker answering maybe I could have transferred the repo.

I take the chance to thank you all again for maintaining `faker` :)

**Pull request merged**
