### PR TITLE
Per generator seeding

### PR DESCRIPTION
**Pull request by reverbc**
This PR is intended to fix the issue in #349.

After let all the providers using the same generator, we should be able to have the following behavior:

```
>>> import faker
>>> # making sure seeding in separate faker instance will have the same results
...
>>> f1 = faker.Faker()
>>> f2 = faker.Faker()
>>> f1.seed(123)
>>> f1.address()
'4106 Peterson Center\nEast Matthew, LA 20619'
>>> f2.seed(123)
>>> f2.address()
'4106 Peterson Center\nEast Matthew, LA 20619'
>>> f1.address()
'7101 David Brooks\nRhondashire, MT 70458-7398'
>>> f2.address()
'7101 David Brooks\nRhondashire, MT 70458-7398'
>>>
>>> # seed module in f1 and should have the same outcome in fm1 and fm2 as they're using module level random obj
...
>>> fm1 = faker.Faker()
>>> fm2 = faker.Faker()
>>> f1.seed_module(456)
>>> fm1.address()
'6098 Mark Terrace Apt. 177\nWest Edwardborough, FL 89898-7519'
>>> f1.seed_module(456)
>>> fm2.address()
'6098 Mark Terrace Apt. 177\nWest Edwardborough, FL 89898-7519'
```

By default all the instance will still use the module level random object. Only when first time `instance.seed(int)` being called it will then create a new random object dedicate for the instance.

### CODE REVIEW

**Comment by reverbc** [comment]
@fcurella could you help to review the proposed solution?

**Comment by fcurella** [comment]
I've been thinking about this, and I'm not sure I like the code to switch behavior after the second call to `.seed()`.

I've looked around github and I saw there's quite some code assuming `Faker.seed()` seeds the module.

I'm sorry about walking back on this, but I think the best solution is to leave `.seed()` for the module, and have `.seed_instance()` for the new behavior. I think that's the best tradeoff between having the new functionality, and not breaking any existing code

**Comment by reverbc** [comment]
Thanks for the input. I'll adjust the behavior accordingly and let you know.

**Comment by reverbc** [comment]
@fcurella I've pushed the changes and the behavior has been adjusted to below example:

```
>>> import faker
>>> # making sure seeding in separate faker instance will have the same results
...
>>> f1 = faker.Faker()
>>> f2 = faker.Faker()
>>> f1.seed_instance(123)
>>> f1.address()
'4106 Peterson Center\nEast Matthew, LA 20619'
>>> f2.seed_instance(123)
>>> f2.address()
'4106 Peterson Center\nEast Matthew, LA 20619'
>>> f1.address()
'7101 David Brooks\nRhondashire, MT 70458-7398'
>>> f2.address()
'7101 David Brooks\nRhondashire, MT 70458-7398'
>>>
>>> # seed module in f1 and should have the same outcome in fm1 and fm2 as they're using module level random obj
...
>>> fm1 = faker.Faker()
>>> fm2 = faker.Faker()
>>> f1.seed(456)
>>> fm1.address()
'6098 Mark Terrace Apt. 177\nWest Edwardborough, FL 89898-7519'
>>> f1.seed(456)
>>> fm2.address()
'6098 Mark Terrace Apt. 177\nWest Edwardborough, FL 89898-7519'
```

**Comment by fcurella** [comment]
Looks good! Thank you so much for all your work! ✨

**Comment by reverbc** [comment]
Thanks for the review and comments!

**Pull request merged**
