### PR TITLE
Adresses lack of Polish (pl-PL) company names, issue #811

### LINKED ISSUE #811: No Polish (pl-PL) company suffixes
There are specific Polish company suffixes not present in pl-PL module for company provider.

### Steps to reproduce
1. Open file faker/providers/company/pl_PL/__init__.py
2. Search for class Provider(CompanyProvider)
3. Find there is no company_suffixes definition tuple

### Expected behavior

There should be Poland's specific company_suffixes definition tuple

### Actual behavior

Default english company_suffixes are generated

### PR DESCRIPTION
**Pull request by twkrol**
Added Polish specific:
- company suffixes
- company prefixes
- company formats
- function definition for company prefix

### What does this changes

Provides Polish company names

### What was wrong

No Polish company names were generated

### How this fixes it

Added functionality to generate comon Polish company names

Fixes #811

### CODE REVIEW

**Comment by twkrol** [comment]
Function definition for **company prefix** could be moved from pl-PL to main company provider, as it could be useful for other nationalities too.

**Comment by fcurella** [comment]
> Function definition for company prefix could be moved from pl-PL to main company provider, as it could be useful for other nationalities too.

That means that all other company providers will be required to have `company_prefixes`. Could you check if they all already have it?

**Comment by twkrol** [comment]
Not all countries would use it for sure. So we can:
- leave it where it is (pl-PL), or 
- move to company provider and add empty `company_prefixes` tuple there as well

**Comment by twkrol** [comment]
Added pull request #814 to address mentioned issues at once for convenience, so this #812 can be abandoned.

**Comment by fcurella** [comment]
You need to add `from __future__ import unicode_literals` at the top of the module. Like this: 

```python
 # coding=utf-8
from __future__ import unicode_literals

 from .. import Provider as CompanyProvider
```

**Comment by twkrol** [comment]
Done, thx.

**Comment by fcurella** [comment]
Thank you, @twkrol 

Could you add some tests specific to `company_prefix` on this locale?

**Comment by twkrol** [comment]
Added tests specific to company_prefix and company_suffix.
Have no clue why 2 of 3 tests failed with "NameError: name 'string_types' is not defined" error, as local tests went fine, and this code is a copy of one above.

**Comment by fcurella** [comment]
that's due to a [recent change in `master`](https://github.com/joke2k/faker/pull/816/files#diff-498cf53d35427897613cdfc4b76fc6ea). You should rebase against master (or merge master into your branch) and use `six.string_types` instead

**Comment by twkrol** [comment]
Thanks for help, @fcurella 
Finally passed all tests :)

**Comment by fcurella** [comment]
Thank you! :sparkles:

**Pull request merged**
