### PR TITLE
Add fake automotive vin number function (#1879)

### PR DESCRIPTION
**Pull request by cyanghsieh**
### What does this change

base on https://en.wikipedia.org/wiki/Vehicle_identification_number to create fake vin number data function.

### What was wrong

new provider function

### How this fixes it
Note: I'm not quite familiar with pytest module, therefore I'm not quite confident on creating a new auto test flow for this vin function. Please forgive me.

### CODE REVIEW

**Comment by themattmorris** [comment]
This is cool!  I am also interested in using this feature, so if needed, I'd be happy to collaborate on building the tests for the feature.

**Review by fcurella — CHANGES_REQUESTED** [review]
I'll need tests before I can merge this.

**Comment by themattmorris** [comment]
Looks like @cyanghsieh beat me to it anyways...thanks!

The only thing I wonder if is `test_vin` should be outside of class `_SimplyAutomotiveTestMixin`.  Looks like running as is will run the same exact test for every provider, as it does not depend on any attributes the same way that `test_license_plate` does.  But I'm also not familiar with the overall test strategy of this repo, and maybe this is what it should do?

**Comment by fcurella** [comment]
> The only thing I wonder if is `test_vin` should be outside of class `_SimplyAutomotiveTestMixin`. Looks like running as is will run the same exact test for every provider, as it does not depend on any attributes the same way that `test_license_plate` does. But I'm also not familiar with the overall test strategy of this repo, and maybe this is what it should do?

I think that's ok for now. But we should think of a way to mark methods as locale-independent.

**Review by fcurella — APPROVED** [review]
Thank you!

**Pull request merged**
