### PR TITLE
Fix docstring syntax

### PR DESCRIPTION
**Pull request by matheusfelipeog**
Hi ;)

I fixed all the docstrings I identified as incorrect in all modules.

### CODE REVIEW

**Review by fcurella — CHANGES_REQUESTED** [review]
Thank you! Could you check the linting issues?

**Comment by matheusfelipeog** [comment]
> Thank you! Could you check the linting issues?

Fixed the file I modified @fcurella ;)

Apparently there are other errors that were added in this commit: https://github.com/joke2k/faker/commit/0ebe46fc9b9793fe315cf0fce430258ce74df6f8

image

I'll fix that as well, as it's part of the context of this PR.

**Comment by matheusfelipeog** [comment]
@fcurella Done ✔

**Comment by fcurella** [comment]
Thank you! <3

**Pull request merged**
