### PR TITLE
:sparkles: - Emoji provider added (#1686).

### PR DESCRIPTION
**Pull request by Artmorse**
### What does this change

I've create a new provider for the 'emoji' generation.

### What was wrong

This feature didn't exist.

### How this fixes it

The feature has been added.

### CODE REVIEW

**Comment by Artmorse** [comment]
I've created a new provider but if you want, I can add the feature in the *internet* one.

**Review by fcurella — APPROVED** [review]

**Review by fcurella — CHANGES_REQUESTED** [review]
can you run `make lint` to fix the linting issues?

**Comment by joke2k** [comment]
Hi, thank you for this PR... nowadays is very easy with python 3.
Take a look on https://github.com/joke2k/faker/pull/777 if you want to improve the provider.

**Comment by Artmorse** [comment]
I've fixed my linter issues and the old ones. :)

**Comment by stefan6419846** [comment]
It seems like the tests still need an adjustment to be successful.

**Comment by Artmorse** [comment]
For this CI issue I don't have any ideas of resolution... If someone can guide me.

The issue:
image

**Comment by Artmorse** [comment]
Please someone can help me on this PR ?
@fcurella @joke2k @stefan6419846

**Comment by fcurella** [comment]
Hi, I’ll be on vacation for the next month or so, so I won’t be able to
help right away.

**Comment by stefan6419846** [comment]
As it seems like merging this PR would already require resolving merge conflicts, could you try to rebase your changes on the latest `master` branch? Looking at the latest action runs, this issue (which probably has been introduced by a *mypy* update) seems to have been fixed in the meantime.

**Review by fcurella — COMMENTED** [review]
I'll take it from here. Feel free to submit more PRs to improve it :) Thank you!

**Pull request merged**
