### PR TITLE
Drop Python 2.6 support

### PR DESCRIPTION
**Pull request by adamchainz**
Ref #363, required so we can use `OrderedDict` without an extra dependency, plus it's super old and insecure.

### CODE REVIEW

**Comment by fcurella** [comment]
@joke2k If you're ok with dropping py2.6, I plan to merge this on Monday.

**Comment by fcurella** [comment]
merged in 68b8ebad112a0a12f47b963ebd62a1abfef3b3ff

**Comment by adamchainz** [comment]
Yay thx. I'll look into the `OrderedDict` fix now.

**Comment by fcurella** [comment]
Thanks, very much appreciated :)

**Pull request closed without merging**
