### PR TITLE
Add unicode string provider

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Comment by jtojnar** [comment]
Any idea why does `test_documentor` fail?

**Comment by MrCsabaToth** [comment]
Can someone tell me how to get unicode texts by the faker. Is there another provider if this one is rejected?

**Comment by jtojnar** [comment]
Feel free to pick this up if this makes sense to you.

**Comment by MrCsabaToth** [comment]
@jtojnar So there isn't any right now? Why this was not merged? Faker without the unicode texts is kind of surprises me.

**Comment by jtojnar** [comment]
No idea. We were using fauxfactory in hamster-gtk and I wanted to use just faker https://github.com/jtojnar/hamster-gtk/commit/e1bd153b72b0eb8403b236feab383be53f3a8a9d but I no longer participate in its development.

**Pull request closed without merging**
