### PR TITLE
Mention ``faker-file`` package

### PR DESCRIPTION
**Pull request by barseghyanartur**
Mention [faker-file](https://pypi.org/project/faker-file/) package.

- [PyPI](https://pypi.org/project/faker-file/)
- [GitHub](https://github.com/barseghyanartur/faker-file/)
- [Documentation](https://faker-file.readthedocs.io/en/latest/?badge=latest)
- [Tests](https://github.com/barseghyanartur/faker-file/actions/workflows/test.yml)
- [License](https://github.com/barseghyanartur/faker-file#license)

### What does this change

Mention [faker-file](https://pypi.org/project/faker-file/) package.

### What was wrong

Nothing. Just adding a reference to a new ``faker`` based package to the docs.

### How this fixes it

Mentions reference to ``faker-file`` in the ``faker`` documentation.

### CODE REVIEW

**Comment by stefan6419846** [comment]
CI still fails:

> /home/runner/work/faker/faker/docs/communityproviders.rst:24: D002 Trailing whitespace

**Comment by barseghyanartur** [comment]
Trailing whitespace issue is fixed.

**Comment by barseghyanartur** [comment]
Ping

**Comment by stefan6419846** [comment]
Flavio being a collaborator with merge privileges mentioned that PRs will not get merged until January due to being on vacation, so there will not be corresponding activity until then (as the most obvious things have already been fixed here).

**Comment by barseghyanartur** [comment]
@stefan6419846:

Thanks for the update!

**Pull request merged**
