### PR TITLE
``hu_HU`` corrections

### LINKED ISSUE #651: Summary ticket for ``hu_HU`` provider
Summary ticket for issues with the ``hu_HU`` provider (I'm working on a PR to fix these).

- [x] ``providers.address.street_name`` (and descendants): incorrectly capitalises street/place/etc.
- [x] ``providers.address.street_address_with_county``: does not capitalise place name
- [x] ``providers.automotive.license_plate``: seems to be the UK licence plate structure, the correct Hungarian licence plate regex is ``\d{3}-[A-Z]{3}``
- [x] ``provides.company.company_suffix``: misspellings and miscapitalizations (e.g. ``Zrt.`` as ``ZRT``
- [x] ``providers.job``: this could be replaced with a professions list from KSH

### PR DESCRIPTION
**Pull request by chrisvoncsefalvay**
### What does this changes

This fixes some of the issues discussed in #651 

### What was wrong

* In some addresses, the name of the public space ('street', 'place' etc.) was capitalised. This is incorrect in Hungarian.
* In some addresses, the place name was not capitalised.
* The license plate format did not align with the Hungarian format.
* The list returned for jobs was the base English list.
* Some company form suffixes were erroneously capitalised.

### How this fixes it

* Capitalisation of public space names is now fixed.
* Place type capitalisation is fixed.
* License plate formatting is fixed.
* Specific ``Provider`` class created for locale ``hu_HU`` and a list, drawn from the KSH's national employment survey nomenclature (FEOR '08), was provided to return job names in Hungarian.
* Capitalisation of company form suffixes fixed.
* Tests written for all of these.

Fixes #651

### CODE REVIEW

**Comment by fcurella** [comment]
can you revert e3cf379? I have a different process for releasing new version. I'll release one as soon as this PR gets merged.

**Comment by chrisvoncsefalvay** [comment]
Sure, I'll push a new version without that commit.

**Comment by chrisvoncsefalvay** [comment]
@fcurella reverted ;)

**Comment by fcurella** [comment]
Thank you @chrisvoncsefalvay ! ✨

**Comment by fcurella** [comment]
@chrisvoncsefalvay [Faker v0.8.7](https://pypi.org/project/Faker/) has been released to PyPI

**Comment by chrisvoncsefalvay** [comment]
👍

**Pull request merged**
