### PR TITLE
Add requirements file + py2.6 handled in travis

### PR DESCRIPTION
**Pull request by gtnx**
Handle issue #211

### CODE REVIEW

**Comment by fcurella** [comment]
wouldn't this install the `importlib` package also for python 2.7+? Or does `importlib`'s own `setup.py` switch to a no-op in that case?

**Comment by gtnx** [comment]
There's a test on the version in the [setup.py](https://github.com/brettcannon/importlib/blob/master/setup.py)

**Comment by fcurella** [comment]
Thanks @gtnx ,

I just checked importlib under py2.7. Looks like it doesn't actually install any python code under those circumstances, but I still don't like having `pip` fetch it for nothing.

I'm ok including it as a requirement, but I'd rather have a list declared in `setup.py` rather than use a `requirements.txt`.

Can you amend your PR to have `setup.py` check the python version and build a requirement list accordingly?

**Comment by gtnx** [comment]
Are you sure?
In my opinion, it makes more sense to let the dependency package (ie importlib) decide what to install. 
Plus, having a requirements.txt file is a common and helpful practice since you just need to do `pip install -r requirements.txt` for setting up your environment.

**Comment by fcurella** [comment]
Yeah, I like the idea of keeping other people's build fast by not fetching. I don't see why let them incur a cost that can be avoided.

Re: `requirements.txt`, my opinion (mostly taken from my interpretation of https://caremad.io/2013/07/setup-vs-requirement/) is that `requirements.txt` is for deployments (eg: a website, or an app), while `install_requires` is for libraries. You can still setup the environment by running `pip install -e .`

**Comment by gtnx** [comment]
Ok. done

**Comment by fcurella** [comment]
Looks good! Thanks!

Just waiting for the CI to pass and I'll merge it.

**Comment by gtnx** [comment]
I can't figure out why the CI failed on appveyor. I don't think it's related to my modifications

**Pull request merged**
