### PR TITLE
Added person provider for gu_IN locale with tests

### LINKED ISSUE #2106: Add provider `gj-IN` for Gujarati language
* Faker version:  <= 29.0.0
* OS: all

There is no provider for Gujarati language in faker

### Expected behavior

There should be a new provider

### Actual behavior

No Provider for `gj-IN`

### PR DESCRIPTION
**Pull request by debjeetsingha**
### What does this change

Added male and female names with prefixes for gu_IN
Added tests for person provider

### What was wrong

There was no person provider for gu_IN locale

Fixes #2106

### Checklist

- [x] I have read the documentation about [CONTRIBUTING](https://github.com/joke2k/faker/blob/master/CONTRIBUTING.rst)
- [x] I have run `make lint`

### CODE REVIEW

**Review by fcurella — APPROVED** [review]
Thank you!

**Review by fcurella — CHANGES_REQUESTED** [review]
Isn't the locale code for Gujarati `gu` instead of `gj`?

https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=gu

**Comment by debjeetsingha** [comment]
The error seems to be related to the use of functools.cache, which was introduced in Python 3.9 with functools.cache. However, Python 3.8 does not support this feature.

**Review by fcurella — APPROVED** [review]
Thank you!

**Comment by wh0th3h3llam1** [comment]
@fcurella It's a debatable topic, but I believe it should be kept as `gj` and not `gu`. The reasons are
- number plates use `GJ`
- it's already mentioned as `GJ` in [State Abbr variable](https://github.com/joke2k/faker/blob/master/faker/providers/address/en_IN/__init__.py#L407)
- [Indian Gov website](https://slusi.da.gov.in/watershedatlas/list_of_state_abbreviation.htm) mentioning state abbr also says `GJ`

I also saw that it's added as `gu` in [language_local_codes](https://github.com/joke2k/faker/blob/master/faker/providers/__init__.py#L156).

Would like to know your thoughts on this. We should probably keep it consistent everywhere and I'm inclined towards `GJ`

**Comment by fcurella** [comment]
We are talking just about the language, not the state.

We follow [ISO-639](
https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=gu),
where it’s defined as `gu`. Every other place where the language code used
is `gj` is incorrect and needs to be fixed.

**Pull request merged**
