### PR TITLE
Create new currency provider pricetag()

### PR DESCRIPTION
**Pull request by eumiro**
This is a new currency provider `pricetag()` that creates a random price in the respective local currency using the format for thousands/decimals.

In the current version, a random price between 0.00 and 99,999.99 is returned for all currencies.

As an example I added the localizations for cs_CZ, de_AT, de_DE, en_AU, en_CA, en_US, es_ES, fr_CA, fr_FR, it_IT, pl_PL, ru_RU, and sk_SK.

The base unlocalized class returns the ISO-Code of a random currency. The localized versions use national currencies (or Euro) of the respective countries.

### CODE REVIEW

**Comment by fcurella** [comment]
Hi @eumiro,

we refactored our test suite to use our new `pytest` plugin. Do you mind update your new tests? Sorry about the merge conflict!

**Comment by eumiro** [comment]
No problem, happy to see new test infrastructure.
How is it with unlocalized instance? Does it default to `en_US`? For instance here in `pricetag()` I generate random currency when unlocalized, `$ …` when `en_US`. The coverage says the unlocalized `pricetag()` is never tested.

**Comment by eumiro** [comment]
@fcurella, rebased, repushed. Now it looks just like a coverall issue.

**Comment by eumiro** [comment]
More green stuff! :tada:

**Review by fcurella — APPROVED** [review]

**Pull request merged**
