### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by vlad-ki**
Add new parameter in to classmethod 'random_number'. It's allow to create random number with fixed lenght.

### CODE REVIEW

**Comment by vlad-ki** [comment]
Hi, tell me please - where may I find the tests for classmethod 'random_number'. Sorry, I do not find it myself.

**Comment by kevin-brown** [comment]
It looks like the tests are in [`faker.tests`](https://github.com/joke2k/faker/blob/c4d142734ba939ecc99e78cd46f9c34f8bca93fc/faker/tests/__init__.py) but there are not any for `random_number`. I suspect it wouldn't be too difficult to create a few though, given the fact that other similar tests exist.

**Comment by vlad-ki** [comment]
Sure! Thanks for your answer.

**Comment by fcurella** [comment]
Thank you! ✨

**Pull request merged**
